version: "3.6"
services:

  postgres:
    image: postgres:12
    container_name: mcsp_database
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres

  graphql:
    image: hasura/graphql-engine:v2.9.0-beta.2
    container_name: mcsp_graphql
    ports:
    - "8080:8000"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:root@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: microscope
      HASURA_GRAPHQL_SERVER_PORT: 8000
      HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: "true"

  rest:
    image: postgrest/postgrest:v10.1.2
    container_name: mcsp_rest
    ports:
    - "8087:3000"
    depends_on:
    - "postgres"
    restart: always
    environment:
      PGRST_DB_URI: postgres://postgres:root@postgres:5432/postgres
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      
  # lab:
  #     build: ./src/Microscope.Lab
  #     container_name: mcsp_lab
  #     ports:
  #         - "8081:8888"
  #     environment:
  #         JUPYTER_NO_PASSWORD: "true"
  #     volumes:
  #         - ./src/Microscope.Lab/work:/home/jupyter/work
  
  storage:
    image: bitnami/minio:latest
    container_name: mcsp_storage
    ports:
        - "8082:9000"
        - "8092:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: microscope
      
  api:
    image: microscope/api
    container_name: mcsp_api
    ports:
      - "8086:80"
    depends_on:
      - "postgres"

  proxy:
    image: microscope/proxy
    container_name: mcsp_proxy
    ports:
      - "8084:80"
  
  keycloak:
    image: mihaibob/keycloak:18.0.2-legacy
    container_name: mcsp_identity
    environment:
      # KEYCLOAK_IMPORT: tmp/realm-export.json
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: mcsp_identity
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: microscope
    # volumes:
    #   - ./BuildingBlocks/IAM/Keycloak/realm-export.json:/tmp/realm-export.json
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    # entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - 8083:8080
    depends_on:
      - postgres

volumes:
  db_data: